# GoReleaser configuration for container-use
version: 2

project_name: container-use

before:
  hooks:
    - go mod tidy

builds:
  - id: cu
    binary: cu
    main: ./cmd/cu
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: cu-archive
    ids:
      - cu
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

homebrew_casks:
  - repository:
      owner: dagger # reconfigure if test releasing on your own fork
      name: homebrew-tap
      pull_request:
        enabled: true # enabled so we can publish draft releases, publish them, then merge the tap PR. to be removed later.
    name: container-use
    binary: cu
    skip_upload: auto # if the version is like v0.0.0-rc1, don't make the tap PR.
    commit_author:
      name: container-use-bot
      email: noreply@dagger.io
    url:
      template: "https://github.com/dagger/container-use/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/dagger/container-use"
    description: "Containerized environments for coding agents"
    hooks:
      post:
        install: |
          if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
            system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cu"]
          end

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: dagger # reconfigure if test releasing on your own fork
    name: container-use
  draft: true
  prerelease: auto
  mode: replace
  header: |
    ## container-use {{ .Tag }}

    Download the pre-compiled binaries from the assets below.
  footer: |
    **Full Changelog**: https://github.com/dagger/container-use/compare/{{ .PreviousTag }}...{{ .Tag }}
